name: OWASP ZAP Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZAP workspace
        run: |
          mkdir -p zap-workspace
          chmod 777 zap-workspace

      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              break
            fi
            echo "Still starting... waiting 5s"
            sleep 5
          done

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm --network host \
            -v $(pwd)/zap-workspace:/zap/wrk:rw \
            -e ZAP_HOME=/zap/wrk \
            -u $(id -u):$(id -g) \
            zaproxy/zap-stable zap-baseline.py \
            -t http://localhost:3000 \
            -r /zap/wrk/zap-report.html \
            -d

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-workspace/zap-report.html
