name: OWASP ZAP Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              break
            fi
            echo "Still starting... waiting 5s"
            sleep 5
          done

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-reports
          chmod 777 zap-reports
          docker run --rm --network host \
            -v "$(pwd)/zap-reports:/zap/wrk:rw" \
            -u root \
            --security-opt seccomp=unconfined \
            ghcr.io/zaproxy/zaproxy:stable \
            python3 /zap/zap-baseline.py \
              -t http://localhost:3000 \
              -r /zap/wrk/zap-report.html \
              -I || echo "ZAP scan completed"

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-reports
          path: zap-reports/
